---

- name: configure postfix master.cf
  template:
    src: 'etc/postfix/master.cf/{{ postfix_role }}.j2'
    dest: '{{ postfix_cfg_dir }}/master.cf'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: postfix_etc_t
    selevel: s0
  notify:
    - 'postfix check config and reload'
  tags:
    - 'role::postfix'
    - 'role::postfix:config'

- name: configure postfix main.cf
  template:
    src: 'etc/postfix/main.cf/{{ postfix_role }}.j2'
    dest: '{{ postfix_cfg_dir }}/main.cf'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: postfix_etc_t
    selevel: s0
  notify:
    - 'postfix check config and reload'
  tags:
    - 'role::postfix'
    - 'role::postfix:config'

- name: configure aliases
  lineinfile:
    name: '{{ postfix_aliases_file }}'
    regexp: '^{{ item.name }}:'
    line: '{{ item.name }}: {{ item.alias }}'
  tags:
    - 'role::postfix'
    - 'role::postfix:config'
  with_items: '{{ postfix_aliases }}'
  notify:
    - 'postfix reload aliases'


- stat:
    path: "{{ postfix_virtual_aliases_file }}"
  register: st

- name: Create file for virtual aliases
  file: 
    path: "{{ postfix_virtual_aliases_file }}"
    state: touch
  when: st.stat.exists == False

- name: configure virtual aliases
  lineinfile:
    name: '{{ postfix_virtual_aliases_file }}'
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} {{ item.alias }}'
  tags:
    - 'role::postfix'
    - 'role::postfix:config'
  with_items: '{{ postfix_virtual_aliases }}'
  notify:
    - 'postfix reload virtual aliases'
