---

- name: postfix check config
  command: '{{ postfix_bin }} -c {{ postfix_cfg_dir }} check'

- name: postfix check config and reload
  command: '{{ postfix_bin }} -c {{ postfix_cfg_dir }} check'
  notify:
    - 'postfix reload daemon'

- name: postfix restart daemon
  service:
    name: '{{ postfix_service }}'
    state: restarted

- name: postfix reload daemon
  service:
    name: '{{ postfix_service }}'
    state: reloaded

- name: postfix reload aliases
  command: '{{ postfix_postalias }} {{ postfix_aliases_file }}'

- name: postfix reload virtual aliases
  command: '{{ postfix_postmap }} {{ postfix_virtual_aliases_file }}'

